### ISSUE TITLE
no audio

### ISSUE THREAD

**Issue by just-rich** [leinstay/discobot#10]
bot is displayed like its sending audio (green circle around avatar) but there is no sound coming from it

**Comment by shelomito12** [comment]
same issue. Getting this error:
```
2021-12-30 16:30:04: Estatus: Error cd conexión al canal
2021-12-30 16:30:04: Error: Could not find an Opus module! Please install @discordjs/opus, node-opus, or opusscript.
2021-12-30 16:30:04:     at new OpusStream (/home/ubuntu/discobot/node_modules/prism-media/src/opus/Opus.js:42:13)
2021-12-30 16:30:04:     at new Encoder (/home/ubuntu/discobot/node_modules/prism-media/src/opus/Opus.js:130:5)
2021-12-30 16:30:04:     at AudioPlayer.playPCMStream (/home/ubuntu/discobot/node_modules/discord.js/src/client/voice/player/BasePlayer.js:58:34)
2021-12-30 16:30:04:     at AudioPlayer.playUnknown (/home/ubuntu/discobot/node_modules/discord.js/src/client/voice/player/BasePlayer.js:53:17)
2021-12-30 16:30:04:     at VoiceConnection.play (/home/ubuntu/discobot/node_modules/discord.js/src/client/voice/util/PlayInterface.js:71:28)
2021-12-30 16:30:04:     at initDispatcher (/home/ubuntu/discobot/index.js:82:38)
2021-12-30 16:30:04:     at /home/ubuntu/discobot/index.js:61:4
```

**Comment by shelomito12** [comment]
fyi, I tried running the following which did the trick:
```
npm i discordjs/opus
```

**Comment by SugarD-x** [comment]
You may have forgotten to install the application through NPM first. `@discordjs/opus` is one of the dependencies listed within `package.json`.

**Comment by leinstay** [comment]
Don't forget to install all dependencies, `npm i discordjs/opus` is mandatory. If for some reason you can't install opus, try `npm i opusscript`
