### ISSUE TITLE
ERROR VOICE_CONNECTION_TIMEOUT bot stopped connecting on March 20th, 2023

### ISSUE THREAD

**Issue by shelomito12** [leinstay/discobot#20]
Getting this error:
```
Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.
    at VoiceConnection.authenticateFailed (/home/ubuntu/discobot/node_modules/discord.js/src/client/voice/VoiceConnection.js:304:26)
    at /home/ubuntu/discobot/node_modules/discord.js/src/client/voice/VoiceConnection.js:325:61
    at Timeout.<anonymous> (/home/ubuntu/discobot/node_modules/discord.js/src/client/BaseClient.js:83:7)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  [Symbol(code)]: 'VOICE_CONNECTION_TIMEOUT'
}
```
Thoughts?

**Comment by RobinDev03** [comment]
Same Problem here

**Comment by SoftCreatR** [comment]
Same problem here. Looks like it's pretty outdated.

**Comment by Ximerixx** [comment]
It is hell oudated, i think i'll try to make it working again

**Comment by Mongstaen** [comment]
Same here!
Did you find a fix for this?

**Comment by emar** [comment]
I have this bot hosted on repl.it and it still runs in my Discord channel.
Forget what changes I made,, there's no sound when you're in the channel, 
I'm not sure if it's an issue with the mic settings in discord or something else.
Started getting a popup warning in Discord about mic been disabled or similar.
When I fixed that issue and enter the channel with the bot, there's still no audio.
